### ISSUE TITLE
Vulcan does not show reflections while Directx12 does

### ISSUE THREAD

**Issue by goedzo** [xenia-project/xenia#1285]
I made comparison in the rendering with Vulcan and D3d12 build. Noticabile in the vulcan version the reflections are not rendered. See screenshot comparison of the game "Rumble Roses XX"

The clothing displayed has some lightning reflection on them, while the vulcan version has not.
[https://www.dropbox.com/s/5u1kkbh65i3s0bu/reflection.png?dl=0](https://www.dropbox.com/s/5u1kkbh65i3s0bu/reflection.png?dl=0)

Is this possible with vulcan, and where can we add this in the code?

**Comment by jgoyvaerts** [comment]
I told you 4 days ago that you were opening too many garbage pull requests and issues, and that you should think and ask questions in discord before opening stupid issues and pull requests. Clearly that advice was too hard?

Vulkan is lagging behind in features to D3D12 because no developer is currently working on Vulkan. There's no need to open any issues for that.

**Comment by Triang3l** [comment]
I had cubemaps done in the Vulkan renderer back in June, but one more small inaccuracy, one less — doesn't matter much, the whole Vulkan renderer needs a rewrite.
