### ISSUE TITLE
Games are on 5 fps when gameplay starts

### ISSUE THREAD

**Issue by helpmeplsguys** [xenia-project/xenia#1337]
Hello, I downloaded a few games on Xenia. I start those games up and in the menus my fps is solid and smooth. However, when I start the actual gameplay, the fps goes down to 5 fps. I use a Geforce Gtx 1050 GPU. Could it be a problem that my GPU only has 2GB video memory?

**Comment by ZolaKluke** [comment]
This is probably better discussed on the Xenia reddit or Xenia discord, join the discord here and we'll try to help: https://discord.gg/5g93S8H

**Comment by legend800** [comment]
We don't support pirates in any way. Close this and do not post here again. And yeah, your video card sucks and you pc is not powerful enough to run games. Why couldn't you have figured that out on your own....

**Comment by BenNottelling** [comment]
Also, really? You username is "Help me pls guys"? 
Dude, you sound so helpless.

**Comment by TGLTClutch** [comment]
@legend800

what makes you think he is a pirate? nothing in his above post suggests that.

 Don't get into insults. Also GTX 1050 isn't bad and is poweful enough for todays standards.

**Comment by legend800** [comment]
@TGLTClutch 
Are you serious? 
 "I downloaded a few games on Xenia...:"

How did you miss that? That's why I reacted the way I did. 

Also, there's no magic setting that takes a game from 5 fps to 60fps, so it's a pointless question. Obviously, the game is demanding and/or hardware are not enough. So how could we help? There's no settings in Xenia..

**Comment by TGLTClutch** [comment]
@legend800

That snetence could be interpreted as him downloading games on his 360 then setting it uo for xenia. It's a 50/50 sentence. You can't download games on xenia btw

Xenia has low peformance as of now but as it develops I'm pretry sure it will get better peformane.

 Better say that 'Xenia is very demanding due to the way it works as of now and is continuously being improved'. 

He could just be new to github jus tlike me. I just recently started using it and finding instructions may be dificult (I didn't even know where to find the commit links)

I'm not supporting him or anything but seems like it was a bit too agressive to a newcomer.

**Comment by legend800** [comment]
Sure, fair enough.

**Comment by helpmeplsguys** [comment]
Sorry, didn’t mean to make this a big issue.

**Comment by legend800** [comment]
Can you close this issue then please?

**Comment by ReservedRegister** [comment]
The reason to why you must have low fps is because your gpu is mostly likely too weak for Xenia to use to render games. 

So there are two things you can do, get a better gpu or wait until Xenia does not make use of hardware so vigerously

I used a gtx 1050ti 4gb on halo 3 and dont get stable 30 fps

Then bought gtx 1060 and still get fps drops, so must be gpu.

**Comment by Triang3l** [comment]
It's not related to memory, it's just Xenia using awful things to emulate the way framebuffers work on the console.
