### ISSUE TITLE
String overhaul/maintenance

### ISSUE THREAD

**Issue by gibbed** [xenia-project/xenia#1547]
This is a general issue for Xenia. It's been discussed before but I don't think we have an issue for it already?

Basically, it boils down to a bunch of maintenance stuff we need to do, to make things more sane and/or portable:

* Replacement of all `wchar_t`/`wstring` usage for guest chars/strings with `uint16_t`/`u16string`.
    * There's a consideration that `char16_t` is defined to basically be `uint_least16_t`, but guest wide characters are *always* `uint16_t`?
* Custom types (or typedefs?) for our string usage for paths:
    * `guest_path` (u16string)
    * `host_path` (platform appropriate choice, ie `u16string` on Windows, `u8string` on Linux)
    * Updating anything that touches file paths in any shape or form to use the new types.
    * Replacement of `to_string`/`to_wstring` with better named functions, ie `to_host`/`to_guest`.

**Comment by JoelLinn** [comment]
Afaik u16string is just `typedef basic_string<char16_t> u16string;` Internally. We probably could do typedefs using `uint16_t` for example.

What about internal string usage? Its often `string`, because the apis involved are utf-8 (file contents, imgui etc) but then windows apis are utf-16...
Haven’t looked in detail but maybe its desirable to only have plain `string` where possible, a `guest_string`, `guest_path` and `host_path` types in the shared code, and keep `wstring` inside windows platform #ifs?

**Comment by gibbed** [comment]
I would say those are a case-by-case basis, I'm mostly after correcting file path usage and guest string handling.

Are there any Windows APIs we're using that aren't path related, that we would need to care about? The few times we use stuff like `MessageBoxW` are largely hardcoded, IIRC.

**Comment by JoelLinn** [comment]
clang/gcc on x86, arm and risc-v all have `uint16_t`, which by the standard means 
`uint_least16_t` should be exactly 2 bytes as well. Using `std::u16string` for the guest strings together with a `static_assert(sizeof(uint_least16_t) == 2)` should be fine then.
Also wchar_t is signed but that's sort of meaningless I guess(?)

**Comment by gibbed** [comment]
Resolved with the merge of #1554.
