### ISSUE TITLE
Red dead redemption 1 with XENIA and Intel UHD graphics 620

### ISSUE THREAD

**Issue by Redbeard90** [xenia-project/xenia#1578]
Hello!

I'm trying to play RDR 1 with Xenia. I got 8GB of RAM and an intel i5 8250u, with an Intel UHD graphics 620 (lenovo yoga 720). The game loads and I can actually play but it is sooo slow. Do u know if I can change any configurations in XENIA or in RDR1 to make it work properly? even if I loose graphics quality. 

I know that it might be difficult to run such a game with an integrated graphics processor but I thought it was worth asking...

Thank you very much!

Arnau,

**Comment by ZolaKluke** [comment]
If you looked when making the issue it says if you need technical support go to the discord server and the link is there too

**Comment by BiwwytheBoi** [comment]
close it

**Comment by seffw** [comment]
Opening. This is the first result on Google. Discord is not helpful here. Github has it's own issues / questions tracker, and not everyone is a member of Discord.

Let's not ignore a thread that asks a valid question. What is the point to answer and say nothing?

For the OP, I am pretty sure the answer to your question is that it is not possible. Xenia, unfortunately, is built with the assumption of a separate graphics card and powerful machine (even though it is emulating old games, and with the power it needs, you could get better games).

But, I am not 100% sure because so far there I have not found (including on Discord) a concrete answer,

I hope this post will encourage someone who knows to comment here, where it is easily found via a Google search.
