### ISSUE TITLE
Suggestion: Mesh Modding Support on d3d12

### ISSUE THREAD

**Issue by steve-smith9** [xenia-project/xenia#1583]
Could you add mesh modding support on Xenia?
Please refer below picture showing basic concepts.

![mesh-modding](https://user-images.githubusercontent.com/63186993/78500040-3287a300-778f-11ea-8c7f-8bc8b0dc90b4.png)

1. When user press dump key, Xenia dumps all buffers on next draw. Dumped files contain raw vertex buffer and index buffer values.
2. A 3D artist or modder writes and runs a script to import data into modeling software (eg. Blender).
3. Modify mesh.
4. He/she writes and runs a script to export the data.
5. Xenia loads new modded buffer data, and draw them, instead of original buffers.

If it's possible, I can contribute to write a sample script for importing / exporting meshes.

## Why Do We Need This?

 - With above method, we can create mods for **any games**.
 - Many games require **d3d12**, which is not supported by other mesh modding software ([3DMigoto](https://github.com/bo3b/3Dmigoto)).
 - Some games have too **complex file formats**, to modify them directly. For example, encrypted triangle strip chunks of hell.

**Comment by Triang3l** [comment]
Hashing vertex buffer contents alone to identify it would take a lot more processing time than a draw call. Hundreds of times every frame. Most likely just no, plus would badly overcomplicate the architecture for something not only extremely rarely used, but completely out of scope of emulation. The direction we're more likely to go is to make draw calls as lightweight as we can (likely register callbacks settings dirty bits, and then only calling needed update functions in a bit scan loop), because draw call overhead is a major performance issue in Xenia.

**Comment by steve-smith9** [comment]
Oh, I thought hashing doesn't need to be precise, eg. only reading first 3 datas is enough.
Anyway, thanks for quick reply!
