### ISSUE TITLE
Death Smiles II X serious graphic errors occur randomly [D3D12]

### ISSUE THREAD

**Issue by arcadee1977** [xenia-project/xenia#1652]
This game often happen corrupt  images or invisible enemies ( every time an image error occurs in gameplay, the situation is different  ) :

![未标题-1](https://user-images.githubusercontent.com/47111657/93965682-51a5db80-fd95-11ea-893a-4d15940dce2e.jpg)
**corrupt scene images**

![未标题-2](https://user-images.githubusercontent.com/47111657/93965688-566a8f80-fd95-11ea-966f-c2aa49a2b66d.jpg)
**invisible enemies**

**Comment by Etokapa** [comment]
It's probably caching shaders.
https://github.com/xenia-project/game-compatibility/issues/1326

**Comment by illusion0001** [comment]
As stated in issue template, this repository is not for game specific issues.

**Comment by Triang3l** [comment]
@Etokapa Caching shading is totally unrelated because we don't do it the RPCS3 way by dropping draws, the image should be unaffected by occasional delays (as long as the game's CPU timers are not completely broken). Still, even though this issue is interesting, since many games have lots of different graphical issues, they should be posted in the compatibility tracker.
