### ISSUE TITLE
Auto use "Trace Frame" F4 on some games.

### ISSUE THREAD

**Issue by backgamon** [xenia-project/xenia#1668]
On some games SPS happen.
The solution are to use the F4 "Trace Frame" switch for the SPS/issue disapear.
On Deadliest Warrior, after every fight, SPS happen.
Using F4 solve the issue...up to next fight :/

Before:
![1](https://user-images.githubusercontent.com/39404647/98030527-71f39c00-1e11-11eb-93fd-9f82a87c4f15.jpg)
Using F4:
![2](https://user-images.githubusercontent.com/39404647/98030543-7b7d0400-1e11-11eb-8632-61202fc34e2d.jpg)
Before:
![3](https://user-images.githubusercontent.com/39404647/98030561-820b7b80-1e11-11eb-8a81-e2a8e0cd549b.jpg)
Using F4:
![4](https://user-images.githubusercontent.com/39404647/98030581-89328980-1e11-11eb-84bc-1eab42de8efb.jpg)

Another games having same thing (Bloodrayne/Soulcalibur II HD...)

**Comment by Triang3l** [comment]
Auto-use of F4 or F5 is not a solution because it doesn't fix the core problem (we're aware of its existence, but we don't know exactly why that happens), also it's a side effect of frame tracing functionality that the symptoms of this bug are cleared, not the purpose of it. The more correct button for clearing it is F5, it clears the GPU emulation caches without creating a snapshot of a frame in the Xenia directory.
