### ISSUE TITLE
White/Black Screen on Launch

### ISSUE THREAD

**Issue by SlovakianMan** [xenia-project/xenia#1734]
When launching Xenia, I am greeted with a white or black screen. I am using an Nvidia GPU. (Picture provided below)

[https://drive.google.com/file/d/1ArP4vDwpclSgnDGDGi7tYqlOIIubOPXh/view?usp=sharing](url)

**Comment by SlovakianMan** [comment]
Ah, I'm not the brightest and just realized that I need to attach a game. How would I go about doing that?

**Comment by Margen67** [comment]
Since you didn't see it the first time:
# THIS IS NOT A SUPPORT FORUM! For support, first read the wiki:
# https://github.com/xenia-project/xenia/wiki
#
# If your question wasn't answered there or you need help, proceed here:
# Xenia Discord (#help) - https://discord.gg/Q9mxZf9
# /r/xenia (questions thread) - https://www.reddit.com/r/xenia/
#
# DO NOT CREATE ISSUES ABOUT SPECIFIC GAMES IN THIS REPOSITORY!
# a game specific issue would be e.g. "Game X crashes after you hit a character a certain way"
# A Xenia issue would be e.g. "Kernel export NtDoSomething does nothing"
# For specific games, visit https://github.com/xenia-project/game-compatibility#game-compatibility
#
# Try to create a very concise title that's straight to the point

**Comment by Triang3l** [comment]
File > Open
o_O
