### ISSUE TITLE
(Feature Request) Custom Resolution Scale

### ISSUE THREAD

**Issue by Back2Life888** [xenia-project/xenia#1790]
First of all, I have to explain how the resolution scale works right now.

The Resolution Scale (d3d12_resolution_scale in the xenia.config or xenia-canary.config) has 2 Options. The first option the normal X360 resolution scale (720p) and the second resolution scale is 2560x1440 (1440p). To change resolution scale, you find d3d12_resolution_scale and you change the value. 1 is the default value which is the normal 720p and 2 is the 1440p respectively.

Now onto the actual request. You see, I use a 1080p monitor (1920x1080) and because of how the resolution scale works, I can't set it on 1920x1080 or 1080p. Setting the resolution scale to 1440p still works but it brings a ton of lag because the resolution scale exceeds my monitor's resolution.

**Comment by Triang3l** [comment]
Something like 4, 5, 3x2 may be possible if we generalize rather than specialize the code for each, but anything non-integer is likely never going to happen because of many issues regarding addressing of pixels on both framebuffer and texture sides. The worst blocker is the inability to map varying amounts of pixels to MSAA samples stored like 1x2 or 2x2 non-multisampled pixels.
