### ISSUE TITLE
Halo Combat Evolved Anniversary issue...

### ISSUE THREAD

**Issue by jvhellraiser** [xenia-project/xenia#1815]
Windows 10
Intel I7 9700k
Nvidia 2060 RTX
16gb Ram DDR4 3200 MHZ
Test on Xenia Canary / Latest build Xenia Git (2021/05/20)
For some reason i am getting textures missing on Ships & Character models in overall.. 
![Capture](https://user-images.githubusercontent.com/16488761/119230528-93d11980-baea-11eb-990e-cbf18d7f8e57.PNG)

**Comment by JoelLinn** [comment]
This issue tracker does not track game specific issues. Please create a report on https://github.com/xenia-project/game-compatibility/issues

**Comment by Triang3l** [comment]
It's an issue caused by occlusion queries, which are required for occlusion culling in the Saber Interactive engine games, currently being faked rather than implemented correctly, so only the depth pre-pass is drawn. While this is a valid issue with the emulator, this is just one of the symptoms of the whole feature not being implemented.
