### ISSUE TITLE
REMOTE CODE EXECUTION YOU HAVE BEEN HACKED!

### ISSUE THREAD

**Issue by DocMAX** [xenia-project/xenia#1818]
When i run `xb build` i get this, why?:

```
t420 /usr/src/github/xenia # ./xb build
Building debug...

- running premake...
Error: ...ands/export-compile-commands/export-compile-commands.lua:21: 

┌─────────────────────────────╖
│                             ║
│    REMOTE CODE EXECUTION    ║
│    YOU HAVE BEEN HACKED!    ║
│                             ║
╘═════════════════════════════╝

Your premake shouldn't be running this script!
Upgrade premake-core or apply this patch to it NOW:
https://github.com/premake/premake-core/commit/21c9985f0989932dbcc79d8770458393794a363f.patch

More info about this:
https://github.com/premake/premake-core/issues/1381#issuecomment-732473611


- building (all):debug...
make: *** build/: No such file or directory.  Stop.

ERROR: build failed with one or more errors.
```

**Comment by JoelLinn** [comment]
Because older premake versions indeed were vulnerable. https://github.com/premake/premake-core/issues/1381#issuecomment-732473611
To fix this, you need to run `git submodule update --init` and remove the `.modules` folder.

In fact it was the xenia project who acted quickly after discovering this vulnerability and fixed it (https://github.com/premake/premake-core/pull/1562).
I registered the domain https://packagesrv.com/ so nobody else can exploit this.
If you are using an old version of premake (the build system we use) and are missing premake modules (i.e. by not fetching the git submodules), it will query `packagesrv.com` for it. To notify users that their version is vulnerable, a small dummy module is downloaded:

```lua
local err = [[


┌─────────────────────────────╖
│                             ║
│    REMOTE CODE EXECUTION    ║
│    YOU HAVE BEEN HACKED!    ║
│                             ║
╘═════════════════════════════╝

Your premake shouldn't be running this script!
Upgrade premake-core or apply this patch to it NOW:
https://github.com/premake/premake-core/commit/21c9985f0989932dbcc79d8770458393794a363f.patch

More info about this:
https://github.com/premake/premake-core/issues/1381#issuecomment-732473611
]]

error(err);
```

**Comment by JoelLinn** [comment]
Still, thank's for reporting this, better be safe than sorry
