### ISSUE TITLE
Somebody included every file extension into "supported" category of files when opening files through xenia

### ISSUE THREAD

**Issue by Hasster1** [xenia-project/xenia#1829]
Somebody accidentally added "*" to a list of a supported xenia's files, thought i should report it.
![image](https://user-images.githubusercontent.com/20757715/120902027-b3b62080-c646-11eb-8603-1a2c2dc944f5.png)

**Comment by Triang3l** [comment]
As accidentally as in the Notepad…

**Comment by Triang3l** [comment]
But seriously, STFS packages have no extension. *pirate radar sounds*

**Comment by Razzile** [comment]
Tri's wording is a bit confusing to me so I thought I'd summarize. STFS packages (a package format used by the 360) have no extension so that's why the 'all files' wildcard is there. 

Maybe it might be possible to scan for the STFS header magic and only show those that match but that might be quite inefficient
