### ISSUE TITLE
Android Build-target?

### ISSUE THREAD

**Issue by strikersix23** [xenia-project/xenia#1878]
If there is a build target for Android what is the build enviroment and/or instructions it would be helpful

**Comment by Razzile** [comment]
Android is currently unsupported. It might be one day but would require a lot of work

**Comment by strikersix23** [comment]
Wasnt Triang3l working to that?

**Comment by enthiran01** [comment]
Yes rumor has it that it would take 1 or 2 yrs for completion

**Comment by enthiran01** [comment]
Sir how long would it take to build? By what year we might expect an
emulator from xenia for android

**Comment by Triang3l** [comment]
Some basic makefile creation is possible via `xenia-build setup --target_os android` on the PC.

It's also possible to generate makefiles on Android itself using Termux (for that, simply `python3 xenia-build setup` is enough) — in this case, Premake will be compiled into the Termux internal storage directory (in /data/data/) if the project itself is in the external storage (something like /sdcard/ or /storage/), as files with execute permissions are not allowed in the external storage. However, building the whole project directly on Android likely won't be supported as the only full-blown IDE that runs on Android I'm aware of — AIDE — uses the deprecated Ant build system. The build system supported by Google and used in Android Studio is Gradle — and PC, for obvious convenience and build time reasons, will be the primary development environment. Gradle projects have a completely different directory structure and build configuration, so supporting both Gradle and Ant will result in lots of duplicate work, often difficult to synchronize. Building on Android devices directly will likely be limited to ELF command line tools like tests and xenia-gpu-vulkan-trace-dump for execution via Termux, if supported at all.

As of now, only some mostly platform-independent library components are buildable, such as xenia-base, possibly also the xenia-base-tests test suite, but I can't remember if I've tried it. The possible generation targets are NDK-Build Android.mk makefiles referenced in the Android Studio project (for static and shared libraries) and the usual GNU/Linux makefiles for use within Termux (for static and shared libraries, as well as console apps).

The Android.mk generator currently used is a slightly modified version of [Meoo/premake-androidmk](https://github.com/Meoo/premake-androidmk). It appears to pretty basic and unsupported by the original developer, however. The primary fundamental flaw, if I understand how it's written correctly, is that it considers different target CPU architectures — the target ABIs — separate build configurations (if it exposes them as configurations at all, or just generates Android.mk for only one ABI, I'm not even fully sure about that, the latter would be even worse). This is fine as long as arm64-v8a is the only target, but will cause issues if x86_64 support is added as well. NDK-Build is designed for building for all ABIs declared in APP_ABI in Application.mk in a single execution, with filtering done inside Android.mk if needed. To support multiple architectures that will require different source files (and maybe different compiler arguments, preprocessor definitions, and other things that go into the LOCAL variables in Android.mk), we'll need to write our own Android.mk generator that will, instead of pre-applying Premake architecture filters based on the argument passed to generation, translate them into TARGET_ARCH_ABI conditionals in the resulting Android.mk, so they are resolved at NDK-Build execution time. If I understand correctly, it's possible for Premake generators to see all statements and their filters directly, rather than the result of all filters applied, so the regular Premake will still be suitable, but more investigation is still needed.

No GUI application in Xenia is currently buildable for Android. As of now, Xenia's windowed app lifecycle management isn't Android-friendly — it has a main function and takes the full responsibility of creating the window and running the OS message loop until a quit message is received. This architecture will need to be replaced with a "context" class that will be providing the data needed for initialization (on Android, that will be ANativeActivity, plus the initial Intent containing the "command line" parameters, the game path, etc.; though for mid-execution Intents an additional callback will be needed likely if supporting them makes any sense at all — without working executable switching, or, more precisely, even whole VFS switching, things like changing the currently running game by tapping the XEX/ISO in some file explorer app will be pointless, maybe only via a restart), as well as an interface for interaction with the UI thread loop (which will be implemented using a Xenia-side GetMessage/DispatchMessage loop in WinMain on Windows, for instance, but on Android it will be communicating with the Looper of the UI thread provided by the OS). Plus, clear distinction between the primary window and secondary windows will need to be made (with a single primary window object owned by that context class, so it may receive events from the NativeActivity if it needs them). While on Windows there will be no functional differences between the two, on Android, instead, the former, along with its layout, will be provided externally, while the latter won't be available at all.

To reduce the size of the app, it's likely that, as there will be no multiple entry points named "main" anyway (the name of the entry point that sets up the callbacks for each specific tool can be specified in the android.app.func_name meta-data entry of the specific native activity class), all tools (the emulator itself, as well as the window demo, the HID demo, the trace dump tool, the tests, and so on) will be packaged in a single .so (thus all ConsoleApps and WindowedApps will become StaticLibs). Since there are some process globals (though it'd be better to eliminate them at some point), and running the emulator and the demos, for example, at the same time will be dangerous (also fatal error reporting calls the exit function), every activity will probably run in a separate android:process, and all activities will have the singleTask launch mode (singleInstance will be overkill as it will harm popups if we ever need any). It's a bit inconvenient that you can't make every _instance_ of an activity in a separate process (Android allows that only for different activity _classes_), but the current system is acceptable too.

But as of today, in short, no, on Android, you can't build anything from the Xenia project that will be really usable.

**Comment by strikersix23** [comment]
Termux has advanced fast within the last month gradle, the ndk, vulkan api support, gl4es, alsa, musl libc, all of them work now to some if not most degree, if the major part is graphics, what about using the vulkan on termux. for the ndk ill reference my sources
https://github.com/Lzhiyong/termux-ndk
https://github.com/suhan-paradkar/tewmux-disabled
https://github.com/suhan-paradkar/termux-wayland

for the target a decent apk target look at this project
https://github.com/VDavid003/sm64-port-android

**Comment by Triang3l** [comment]
Yes, launching Gradle from Termux is a viable option as well, but editing won't be very convenient. For audio output, by the way, AAudio seems to be the best option for Android 8+, with an OpenSL ES fallback for older versions (7 is the lowest that supports Vulkan) — though the Oboe library is also usable as an abstraction layer above both.

**Comment by strikersix23** [comment]
Would this help

https://github.com/suhan-paradkar/tewmux-disabled/releases/tag/intellijidea-2021.2

**Comment by strikersix23** [comment]
I also remember somone managing to imbed a custom mesa version in an apk but im trying to find the sources, a big question for me as of currently is does xenia use opengl or vulkan

**Comment by Triang3l** [comment]
A full-scale GNU/Linux IDE via VNC? If your tastes are very singular, yes ;) Xenia will be using Vulkan on Linux, but the Vulkan backend with the new architecture is still missing multiple emulation subsystems, doesn't even work on the PC yet — Android will need additional work, such as emulation of basic memexport cases and rectangle primitives via conversion of vertex shaders to compute shaders when vertex shader storage writes and geometry shaders respectively are not supported, manual big-endian index buffer fetching as a fallback for unsupported 32-bit vertex indices, and lots of other things, with the most complex being deriving brightness deltas and T-mode/H-mode/planar mode usage from S3TC endpoints and lerp factors to generate some ETC2 encoding that will more or less resemble the original S3TC.

**Comment by strikersix23** [comment]
I might have a solution for the shaders and s3tc encoding, the building cannot be on device theres more options then vnc. Well Android might be two years from now, youd be best to target api 29 with the build target, lowest Android 8.1. Hower ever if Android cant be a target now perhaps some work on targeting aarch64 linux for the subsystems could be a good start for a base

**Comment by Triang3l** [comment]
The biggest issue right now is that the whole CPU emulation backend needs to be emitting Armv8 code instead of AMD64.

**Comment by strikersix23** [comment]
Yeah, thats why i said work needed to be done to port subsystems to aarch64/armv8 linux. Doesnt xenia use llvm as a backend or support?

**Comment by Triang3l** [comment]
No, the entire process is custom, with our own intermediate representation, for various reasons why we need as much control as possible (such as status/control flags in the future). Though it's possible that, at least for the beginning, an emitter for the HIR in its current state is created, but there are Arm-specific things to consider such as aliased floating-point and vector registers that can be taken advantage of.

**Comment by enthiran01** [comment]
Sir I would like to ask if ever xenia emulator comes to Android what would
be the minimum requirements and what would be the max requirements and what
snapdrogon is needed to run properly?

**Comment by enthiran01** [comment]
And by what year can we expect emulator from your side? I admire ur work
and efforts taken here alot thnk u for everything

**Comment by Triang3l** [comment]
@enthiran01 This is a place for technical discussion, not for "when" questions. We can't say anything about performance estimates before anything can be launched, there are no even rough references as that's a completely different platform with its own approaches to GPU architecture, as well as significantly lower CPU and GPU power. On PC integrated GPUs, Xenia currently runs very slowly, and with tile loads/stores on mobile I'd expect things to be even worse for now, but there are many areas in GPU emulation that can be optimized, like overly conservative copying between render targets in cases of drawing without clipping (like clears), eliminating unneeded barriers and render pass restarts.

**Comment by enthiran01** [comment]
Thnk u sir for your response  it helped me a lot thnks for the details and
your efforts taken here.

**Comment by Triang3l** [comment]
A basic implementation of callback-based windowed app architecture has been done in 6ce5330f5f240f7ea5bcd06a49794480a339860a, along with moving all UI work to the platform's thread that launched the windowed app. OnInitialize (for calling in Android's onCreate after instantiating the AndroidWindowedAppContext and the WindowedApp) and OnDestroy (for onDestroy) callbacks are currently exposed. Various other callbacks will need to be proxied in the future — possibly not as WindowedApp entry points, but as calls to functions of the main Window that should be registered in the AndroidWindowedAppContext, for more consistency between different windowing backends (as Windows and GTK+ callbacks are implemented in the Window class as well) and better encapsulation of window-related logic, as well as to reduce code duplication between apps (though that can be solved with self-registration of windows as handlers rather than via directly implementing the handlers in subclasses). Those callbacks include configuration changes (like size and DPI), surface recreation (though with a custom Activity class, we'll possibly have more control of when that happens, so maybe we will be able to tie SurfaceView lifecycle operations to some other events that result in them). One potential callback which may not be a Window one, but rather specifically a WindowedApp one, is for receiving an Intent (possibly exposed in a platform-independent way as argc/argv, but to a callback rather than the main function).

**Comment by nonetrix** [comment]
Would be cool but I doubt any phone would be able to run it

**Comment by strikersix23** [comment]
Hey @Triang3l thanks for the work, i appreciate it

**Comment by Triang3l** [comment]
The ndk-build script generator has been replaced with [a custom one](https://github.com/Triang3l/premake-androidndk), which supports architecture filters. Running ndk-build from the current Gradle scripts works, so the build system invocation part may be considered a solved issue. The path to `libxenia.so` with demos is still pretty long, however, and will be something to possibly open other issues for.
