### ISSUE TITLE
sonic unleashed black screen 

### ISSUE THREAD

**Issue by fort-za** [xenia-project/xenia#1918]
[//]: # (Describe what's going wrong:)

[//]: # (Describe what should happen:)

[//]: # (If applicable, provide a callstack here - esp. for crashes)

[//]: # (If applicable, upload a logfile and link it here)

**Comment by Triang3l** [comment]
A well-known issue, but prefer posting game-specific issue reports in the game's entry in the compatibility tracker — https://github.com/xenia-project/game-compatibility/issues/300 (unless the issue report is something expressed in terms of the console's internals as opposed to visible symptoms). Closing because no information is provided aside from a vague description of the visual effect.

**Comment by Codexmsters** [comment]
reopen
