### ISSUE TITLE
Sonic Unleashed crashes in first Level

### ISSUE THREAD

**Issue by ZaHando69** [xenia-project/xenia#2042]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [X] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

My game always goes very buggy in one specific part of the first level and if i try to go further the screen goes black

### Describe what should happen

The game shouldnt go black

**Comment by Margen67** [comment]
🤓🤓🤓🤡🤡🤡🤡

**Comment by ZaHando69** [comment]
> 🤓🤓🤓🤡🤡🤡🤡

?

**Comment by bomabomaboma** [comment]
> did i do something wrong?

The issues Xenia has with Sonic Unleashed are well-known. This is not the correct place to report on game compatibility, that is reserved for [https://github.com/xenia-project/game-compatibility/issues](url)

**Comment by ZaHando69** [comment]
Oh sorry for bothering you

**Comment by Darkhost1999** [comment]
None of this is supposed to be against you in any way.
The issues created here are for emulator issues not emulation issues as emulation issues go https://github.com/xenia-project/game-compatibility/issues

If you know how to debug what the emulator is doing that is wrong and inform us about the function, the output, the intended function, and the intended output we would love to revisit this issue and see if we can maybe even solve the problem.

If you don't know how to debug the issue we would absolutely love and appreciate obtaining updates for all of your games over https://github.com/xenia-project/game-compatibility/issues
I most certainly want to learn about recent information over there instead of anything that's older than 3 months since the last update.
