### ISSUE TITLE
Add Intel C++ Compiler compatibility?

### ISSUE THREAD

**Issue by thx4ever** [xenia-project/xenia#595]
Its possible to add intel compiler compatibility? Right now it fails to compile xenia kernel, libavc and libavutils
[xenia kernel build log.txt](https://github.com/benvanik/xenia/files/344151/xenia.kernel.build.log.txt)
 I fixed libavutil and libavc adding C++99 language extension and it compiled just fine, now the problem are in xenia kernel include file \src\xenia\kernel\util\shim_utils.h

**Comment by jobs-git** [comment]
Intel C++ is proprietary, we got to pay to get it tested and pay to got apps to deploy, unless you are making a computational software its got advantage due to its fast math algorithm.

Mind you, successful apps and successful developers use just typical compilers.

**Comment by JohnHolmesII** [comment]
>we got to pay to get it tested and pay to got apps to deploy
wrong

Intel provides licenses for OSS.
https://software.intel.com/en-us/qualify-for-free-software/opensourcecontributor

There is a travis issue (closed by a bot for no reason) asking for ICC support. The issue is the auto licensing feature on intel's side. Someone wrote a script [here](https://github.com/nemequ/icc-travis) that gets builds working with travis as-is, but the vms will eventually burn through the activation limit. However, if CI were ever set up on a dedicated server, it could work out.

As an aside, rolling back to c++99 is a solution to exactly 0 real problems.

**Comment by jobs-git** [comment]
I dont know if it was wrong that time, todays 2019, Im glad they have it oss now
