### ISSUE TITLE
About fundraising for Xenia developers

### ISSUE THREAD

**Issue by SauronfromMordor** [xenia-project/xenia#645]
Hello! As I know developers say that they don't have AMD card (and can't make support because of it). And the only way to get it - it's fundraising through [the site](http://xenia.jp/).
![1](https://cloud.githubusercontent.com/assets/24421310/20949315/c23071dc-bc29-11e6-9a69-c220be6eee03.png)
And I've got the idea: this fundraising may be reorganized. It should be better to place a donation scale with text "for AMD card" or smth instead of abstract button. Many people want to know where their money'll go, and there'll be more chances that they'll donate.
P.S. Oops, I went to [changetip](https://www.changetip.com/wallet) and saw next: "ChangeTip will be [discontinuing services soon](https://www.reddit.com/r/changetip/comments/5dn3rc/changetip_shutting_down). Please close your account from the [account settings](https://www.changetip.com/account#close) page." It would be good to hear some comments from developers.

**Comment by Razyre** [comment]
100% agree, I'd love to put some money in the pot to get an active dev an AMD card. Anything to see Xenia move forward.

**Comment by XeClutch** [comment]
Not sure that they would be allowed to take monetary donations because at that point they'd be profiting off Microsoft since all Xenia does is emulate the 360. Could be wrong though. I just know that when I used to work on Installation 01 we couldn't make any money on it or take donations since it was a fan-made Halo game.

**Comment by resetnow** [comment]
Luckily for us, many of the world's businessmen and politicians have faced this problem before and have had it resolved. Developers just need to open a totally unrelated non-profit foundation, preferably in some island country. The purpose of the foundation would be to help aspiring open-source developers like themselves.

**Comment by SauronfromMordor** [comment]
@XeClutch, of course, I thought about a legal side of it. But developers of another emulators like [ePSXe](http://epsxe.com/) and [PPSSPP](https://ppsspp.org/) distribute paid versions of them, and even in Google Play with its loyalty to laws.
Yeah, I understand that Microsoft isn't Sony, but @DrChat may discuss it with them, maybe they use @resetnow's method.
P.S. Changetip button has to be removed in any case, the service will be shut down soon.

**Comment by vgturtle127** [comment]
@XeClutch That's because you were using copyrighted and trademarked characters and words and what not. Xenia uses nothing that is copyrighted, and to boot is free, open-source software. So Microsoft can't do anything to stop the Xenia team from accepting donations. Which is good. 😄 

@SauronfromMordor @resetnow is talking about creating a non-profit organization, which seems a bit complex if all you want to do is accept donations. I would just get a PayPal going, or setup a BitCoin or something. No need to go through all the hassle of setting up a non-profit and all that.

**Comment by XeClutch** [comment]
@vgturtle127 Actually we weren't using any of Microsoft's assets. The name Halo was never mentioned in the game (aside from when referring to the ring in space) and we made all of the assets and wrote all of our code on our own.

Fact of the matter is, this isn't very different than Apple stealing from IBM (or w/e that movie was about). You have someone reverse-engineering someone else's trademarked/registered/copywritten/etc.. product and then reselling that product in the form of an emulator. Or in this case, taking money to continue development on said product which could potentially mean Microsoft is losing money. I'm more than sure that Ben Vanik and the rest of the Xenia devs are operating within the confines of the law right now, but I'm fairly certain that if they started taking donations on this project they could find themselves in a very expensive, gray area that Microsoft is, more than likely, willing to get involved in.

However, @resetnow had an excellent idea. Setting up a fundraising campaign for something unrelated would be an excellent idea.

**Comment by Razyre** [comment]
Xenia the dog needs an expensive hair transplant, donate now!

**Comment by vgturtle127** [comment]
@XeClutch Huh, alright. I know for a fact they can't do anything about Xenia, since it isn't using any of Microsoft's property. That's what the Sony vs Bleem and Sony vs VGS cases were about, and in both Sony lost. But anyway, donations could be setup in any form and I am certain that people would donate. 😄

**Comment by SauronfromMordor** [comment]
By the way, RPCS3 developers [have created](https://github.com/RPCS3/rpcs3/issues/2263#issuecomment-274214820) Patreon campaign! ([link](https://www.patreon.com/Nekotekina))
Meanwhile, you can spend your extra cash there :smile:

**Comment by Razyre** [comment]
I was going to mention this

**Comment by DrChat** [comment]
I've opened a fund for an AMD card [here](https://fundrazr.com/81DYF1). See: #578.

**Comment by Razyre** [comment]
Thank you DrChat! :) Will throw some money in there when I get paid!

**Comment by minuteworld** [comment]
I'll think about funding if they decide to go that route if they add support for windows 7.

**Comment by DrChat** [comment]
Update: I had some plans for donating to the project directly, but haven't been working on them as of late.

**Comment by hcorion** [comment]
This issue seems to now be fixed with the release of a patreon: https://www.patreon.com/xenia_project

**Comment by DrChat** [comment]
Indeed! Appreciate it.
